import type { AnchorDefinition, DynamicFieldDefinition } from "../types";

const unit = {
  ton: ["TON"],
  liter: ["LITER", "LITRE"],
  day: ["HARI", "DAYS"],
} as const;

const currentAliases = (label: string) => [
  `${label} CURENT`,
  `${label} CURRENT`,
  `${label} TERKINI`,
];

export const DASHBOARD_FIELD_DEFINITIONS: readonly DynamicFieldDefinition[] = [
  {
    field: "biomassReceiptMonthly",
    key: "biomassReceiptMonthly",
    label: "TOTAL PENERIMAAN BIOMASSA BULANAN",
    aliases: ["TOTAL PENERIMAAN BIOMASSA", "PENERIMAAN BIOMASSA BULANAN"],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "biomassConsumptionMonthly",
    key: "biomassConsumptionMonthly",
    label: "TOTAL PEMAKAIAN BIOMASSA BULANAN",
    aliases: ["TOTAL KONSUMSI BIOMASSA BULANAN", "PEMAKAIAN BIOMASSA BULANAN"],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "biomassUnit1Current",
    key: "biomassUnit1Current",
    label: "PEMAKAIAN BIOMASSA UNIT 1 CURENT",
    aliases: currentAliases("PEMAKAIAN BIOMASSA UNIT 1"),
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "biomassUnit2Current",
    key: "biomassUnit2Current",
    label: "PEMAKAIAN BIOMASSA UNIT 2 CURENT",
    aliases: currentAliases("PEMAKAIAN BIOMASSA UNIT 2"),
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "biomassUnit3Current",
    key: "biomassUnit3Current",
    label: "PEMAKAIAN BIOMASSA UNIT 3 CURENT",
    aliases: currentAliases("PEMAKAIAN BIOMASSA UNIT 3"),
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalConsumptionMonthly",
    key: "coalConsumptionMonthly",
    label: "TOTAL PEMAKAIAN BATUBARA BULANAN",
    aliases: ["TOTAL PEMAKAIAN BATU BARA BULANAN", "PEMAKAIAN BATUBARA BULANAN"],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalReceiptMonthly",
    key: "coalReceiptMonthly",
    label: "TOTAL PENERIMAAN BATUBARA BULANAN",
    aliases: ["TOTAL PENERIMAAN BATU BARA BULANAN", "PENERIMAAN BATUBARA BULANAN"],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalUnit1Current",
    key: "coalUnit1Current",
    label: "PEMAKAIAN BATUBARA UNIT 1 CURENT",
    aliases: [
      ...currentAliases("PEMAKAIAN BATUBARA UNIT 1"),
      "PEMAKAIAN BATU BARA UNIT 1 CURENT",
      "PEMAKAIAN BATU BARA UNIT 1 CURRENT",
    ],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalUnit2Current",
    key: "coalUnit2Current",
    label: "PEMAKAIAN BATUBARA UNIT 2 CURENT",
    aliases: [
      ...currentAliases("PEMAKAIAN BATUBARA UNIT 2"),
      "PEMAKAIAN BATU BARA UNIT 2 CURENT",
      "PEMAKAIAN BATU BARA UNIT 2 CURRENT",
    ],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalUnit3Current",
    key: "coalUnit3Current",
    label: "PEMAKAIAN BATUBARA UNIT 3 CURENT",
    aliases: [
      ...currentAliases("PEMAKAIAN BATUBARA UNIT 3"),
      "PEMAKAIAN BATU BARA UNIT 3 CURENT",
      "PEMAKAIAN BATU BARA UNIT 3 CURRENT",
    ],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalDailyTotal",
    key: "coalDailyTotal",
    label: "TOTAL PEMAKAIAN BATUBARA HARIAN",
    aliases: ["TOTAL PEMAKAIAN BATU BARA HARIAN", "PEMAKAIAN BATUBARA HARIAN"],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalStock",
    key: "coalStock",
    label: "STOK BATUBARA",
    aliases: ["STOCK BATUBARA", "STOK BATU BARA", "STOCK BATU BARA"],
    tableKind: "dashboard",
    expectedUnits: unit.ton,
  },
  {
    field: "coalHop",
    key: "coalHop",
    label: "HOP BATUBARA",
    aliases: ["HOP BATU BARA"],
    tableKind: "dashboard",
    expectedUnits: unit.day,
  },
  {
    field: "solarConsumptionDaily",
    key: "solarConsumptionDaily",
    label: "PEMAKAIAN SOLAR CH HARIAN",
    aliases: ["PEMAKAIAN SOLAR HARIAN", "PEMAKAIAN HSD CH HARIAN"],
    tableKind: "dashboard",
    expectedUnits: unit.liter,
  },
  {
    field: "solarConsumptionMonthly",
    key: "solarConsumptionMonthly",
    label: "TOTAL PEMAKAIAN SOLAR BULANAN",
    aliases: ["TOTAL PEMAKAIAN HSD BULANAN", "PEMAKAIAN SOLAR BULANAN"],
    tableKind: "dashboard",
    expectedUnits: unit.liter,
  },
  {
    field: "solarReceiptMonthly",
    key: "solarReceiptMonthly",
    label: "TOTAL PENERIMAAN SOLAR BULANAN",
    aliases: ["TOTAL PENERIMAAN HSD BULANAN", "PENERIMAAN SOLAR BULANAN"],
    tableKind: "dashboard",
    expectedUnits: unit.liter,
  },
  {
    field: "biomassTarget",
    key: "biomassTarget",
    label: "TARGET PEMAKAIAN BIOMASSA",
    aliases: ["TARGET BIOMASSA", "TARGET 2026", "TARGET 2025"],
    tableKind: "target",
    expectedUnits: unit.ton,
    match: (value) => /^TARGET\s+\d{4}$/.test(value),
  },
  {
    field: "biomassCumulative",
    key: "biomassCumulative",
    label: "KUMULATIF PEMAKAIAN BIOMASSA",
    aliases: ["TOTAL 2026", "PEMAKAIAN 2026", "TOTAL 2025", "PEMAKAIAN 2025"],
    tableKind: "historical",
    expectedUnits: unit.ton,
    match: (value) => /^(?:TOTAL|PEMAKAIAN)\s+\d{4}$/.test(value),
  },
];

export const DASHBOARD_STRUCTURAL_DEFINITIONS: readonly AnchorDefinition[] = [
  {
    key: "dashboardHeader",
    label: "DASHBOARD",
    aliases: ["DASHBOARD SATUAN SUMBER DATA STATUS"],
    tableKind: "dashboard",
  },
  {
    key: "dateHeader",
    label: "TANGGAL",
    aliases: ["TGL", "DATE"],
    tableKind: "daily",
  },
  {
    key: "totalHeader",
    label: "TOTAL",
    aliases: ["TOTAL (TON)", "TOTAL TON"],
    tableKind: "daily",
  },
  {
    key: "hopHeader",
    label: "HOP",
    aliases: ["HARI OPERASI", "DAYS OF OPERATION"],
    tableKind: "daily",
    expectedUnits: ["HARI"],
  },
  {
    key: "stockHeader",
    label: "STOK",
    aliases: ["STOCK", "STOK AKHIR", "STOCK AKHIR"],
    tableKind: "daily",
    expectedUnits: unit.ton,
  },
  {
    key: "solarHeader",
    label: "SOLAR",
    aliases: ["HSD", "SOLAR CH"],
    tableKind: "daily",
    expectedUnits: unit.liter,
  },
  {
    key: "targetYear",
    label: "TARGET",
    tableKind: "target",
    expectedUnits: unit.ton,
    match: (value) => /^TARGET\s+\d{4}$/.test(value),
  },
  {
    key: "historicalYear",
    label: "HISTORICAL YEAR",
    tableKind: "historical",
    expectedUnits: unit.ton,
    match: (value) => /^(?:TOTAL|PEMAKAIAN)\s+\d{4}$/.test(value),
  },
];

