"use client";

import { useState, type KeyboardEvent } from "react";
import type { OverviewDailyPoint } from "@/types/overview";

type SeriesKey = "biomass" | "coal" | "stock" | "solar" | "solarReceipt" | "hop1" | "hop2" | "hop3" | "coalUnit1" | "coalUnit2" | "coalUnit3" | "biomassUnit1" | "biomassUnit2" | "biomassUnit3";
type Dataset = { key: SeriesKey; label: string; color: string };
type ReferenceLine = { value: number; label: string; color: string };
type DetailLineChartProps = { series: OverviewDailyPoint[]; dataKey: SeriesKey; label: string; unit: string; color: string; referenceLines?: ReferenceLine[] };
type DetailMultiLineChartProps = { series: OverviewDailyPoint[]; datasets: Dataset[]; unit: string; referenceLines?: ReferenceLine[] };
type DetailBarChartProps = { series: OverviewDailyPoint[]; datasets: Dataset[]; unit: string; stacked?: boolean };

const WIDTH = 760;
const HEIGHT = 280;
const PADDING = { top: 20, right: 18, bottom: 42, left: 58 };

function valueFor(point: OverviewDailyPoint, key: SeriesKey) { return point[key] ?? null; }
function format(value: number) { return value.toLocaleString("id-ID", { maximumFractionDigits: 1 }); }
function chartBounds(values: number[]) { const min = Math.min(...values, 0); const max = Math.max(...values, 1); return { min, max: max === min ? min + 1 : max }; }
function yFor(value: number, bounds: { min: number; max: number }, plotHeight: number) { return PADDING.top + plotHeight - ((value - bounds.min) / (bounds.max - bounds.min)) * plotHeight; }
function labels(series: OverviewDailyPoint[]) { return series.filter((_, index) => index % Math.max(1, Math.ceil(series.length / 8)) === 0); }
function activateOnKey(event: KeyboardEvent<SVGCircleElement> | KeyboardEvent<SVGRectElement>, callback: () => void) { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); callback(); } }

function EmptyChart({ message }: { message: string }) { return <div className="flex h-64 items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-sm text-slate-500">{message}</div>; }

export function DetailLineChart({ series, dataKey, label, unit, color, referenceLines = [] }: DetailLineChartProps) {
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const available = series.filter((point) => valueFor(point, dataKey) !== null);
  if (!available.length) return <EmptyChart message={`Tidak ada data ${label.toLowerCase()} untuk divisualisasikan.`} />;
  const bounds = chartBounds(available.map((point) => valueFor(point, dataKey) as number));
  const plotWidth = WIDTH - PADDING.left - PADDING.right;
  const plotHeight = HEIGHT - PADDING.top - PADDING.bottom;
  const points = series.map((point, index) => ({ point, x: PADDING.left + (series.length === 1 ? plotWidth / 2 : (index / (series.length - 1)) * plotWidth), y: valueFor(point, dataKey) === null ? null : yFor(valueFor(point, dataKey) as number, bounds, plotHeight) }));
  const path = points.reduce((result, current) => current.y === null ? result : `${result}${result && !result.endsWith("M") ? " L" : "M"} ${current.x.toFixed(2)} ${current.y.toFixed(2)}`, "");
  const selected = selectedDate ? series.find((point) => point.date === selectedDate) : null;
  return <div className="rounded-xl border border-slate-100 bg-slate-50/60 p-2 sm:p-3"><div className="mb-2 flex items-center justify-end gap-2 px-2 text-xs text-slate-600"><i className="size-2 rounded-full" style={{ backgroundColor: color }} />{label}</div><svg className="h-auto w-full" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} role="img" aria-label={`Grafik ${label}`}>
    {[0, 0.25, 0.5, 0.75, 1].map((ratio) => { const y = PADDING.top + plotHeight * ratio; const value = bounds.max - (bounds.max - bounds.min) * ratio; return <g key={ratio}><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={y} y2={y} stroke="#e2e8f0" strokeDasharray="4 4" /><text x={PADDING.left - 8} y={y + 4} fill="#64748b" fontSize="10" textAnchor="end">{format(value)}</text></g>; })}
    {referenceLines.map((line) => { const y = yFor(line.value, bounds, plotHeight); return <g key={line.label}><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={y} y2={y} stroke={line.color} strokeDasharray="6 4" /><text x={WIDTH - PADDING.right} y={y - 4} fill={line.color} fontSize="10" textAnchor="end">{line.label}</text></g>; })}
    <line x1={PADDING.left} x2={PADDING.left} y1={PADDING.top} y2={HEIGHT - PADDING.bottom} stroke="#cbd5e1" /><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={HEIGHT - PADDING.bottom} y2={HEIGHT - PADDING.bottom} stroke="#cbd5e1" /><path d={path} fill="none" stroke={color} strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" />
    {points.map(({ point, x, y }) => y === null ? null : <circle key={point.date} cx={x} cy={y} r={selectedDate === point.date ? 5 : 3} fill={color} stroke="white" strokeWidth={selectedDate === point.date ? 2.5 : 1.5} tabIndex={0} role="button" aria-label={`${point.date}: ${format(valueFor(point, dataKey) as number)} ${unit}`} onMouseEnter={() => setSelectedDate(point.date)} onClick={() => setSelectedDate(point.date)} onKeyDown={(event) => activateOnKey(event, () => setSelectedDate(point.date))}><title>{`${point.date}: ${format(valueFor(point, dataKey) as number)} ${unit}`}</title></circle>)}
    {labels(series).map((point) => { const x = PADDING.left + (series.length === 1 ? plotWidth / 2 : (series.indexOf(point) / (series.length - 1)) * plotWidth); return <text key={`${point.date}-label`} x={x} y={HEIGHT - 16} fill="#64748b" fontSize="10" textAnchor="middle">{point.day}</text>; })}<text x="14" y={HEIGHT / 2} fill="#64748b" fontSize="10" textAnchor="middle" transform={`rotate(-90 14 ${HEIGHT / 2})`}>{unit}</text><text x={WIDTH / 2} y={HEIGHT - 2} fill="#64748b" fontSize="10" textAnchor="middle">Tanggal</text>
  </svg>{selected && valueFor(selected, dataKey) !== null ? <div className="mt-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600"><strong className="text-slate-900">{selected.date}</strong><span className="mx-2 text-slate-300">·</span>{label}: <strong className="text-slate-900">{format(valueFor(selected, dataKey) as number)} {unit}</strong></div> : <p className="mt-2 px-2 text-[11px] text-slate-400">Arahkan atau pilih titik data untuk melihat detail.</p>}</div>;
}

export function DetailMultiLineChart({ series, datasets, unit, referenceLines = [] }: DetailMultiLineChartProps) {
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [hiddenKeys, setHiddenKeys] = useState<Set<SeriesKey>>(new Set());
  const visible = datasets.filter((dataset) => !hiddenKeys.has(dataset.key));
  const hasValue = visible.some((dataset) => series.some((point) => valueFor(point, dataset.key) !== null));
  if (!hasValue) return <EmptyChart message="Pilih minimal satu series untuk divisualisasikan." />;
  const values = visible.flatMap((dataset) => series.map((point) => valueFor(point, dataset.key)).filter((value): value is number => value !== null));
  const bounds = chartBounds(values);
  const plotWidth = WIDTH - PADDING.left - PADDING.right;
  const plotHeight = HEIGHT - PADDING.top - PADDING.bottom;
  const points = series.map((point, index) => ({ point, x: PADDING.left + (series.length === 1 ? plotWidth / 2 : (index / (series.length - 1)) * plotWidth) }));
  const pathFor = (key: SeriesKey) => points.reduce((path, current) => { const value = valueFor(current.point, key); return value === null ? path : `${path}${path && !path.endsWith("M") ? " L" : "M"} ${current.x.toFixed(2)} ${yFor(value, bounds, plotHeight).toFixed(2)}`; }, "");
  return <div className="rounded-xl border border-slate-100 bg-slate-50/60 p-2 sm:p-3"><div className="mb-2 flex flex-wrap items-center justify-end gap-2 px-2 text-xs text-slate-600">{datasets.map((dataset) => <button key={dataset.key} type="button" aria-pressed={!hiddenKeys.has(dataset.key)} onClick={() => setHiddenKeys((current) => { const next = new Set(current); if (next.has(dataset.key)) next.delete(dataset.key); else if (next.size < datasets.length - 1) next.add(dataset.key); return next; })} className={`inline-flex min-h-8 items-center gap-2 rounded-lg px-2 py-1 transition focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 ${hiddenKeys.has(dataset.key) ? "text-slate-400 line-through" : "hover:bg-white"}`}><i className="size-2 rounded-full" style={{ backgroundColor: hiddenKeys.has(dataset.key) ? "#cbd5e1" : dataset.color }} />{dataset.label}</button>)}</div><svg className="h-auto w-full" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} role="img" aria-label="Grafik multi-series">
    {[0, 0.25, 0.5, 0.75, 1].map((ratio) => { const y = PADDING.top + plotHeight * ratio; const value = bounds.max - (bounds.max - bounds.min) * ratio; return <g key={ratio}><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={y} y2={y} stroke="#e2e8f0" strokeDasharray="4 4" /><text x={PADDING.left - 8} y={y + 4} fill="#64748b" fontSize="10" textAnchor="end">{format(value)}</text></g>; })}{referenceLines.map((line) => { const y = yFor(line.value, bounds, plotHeight); return <g key={line.label}><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={y} y2={y} stroke={line.color} strokeDasharray="6 4" /><text x={WIDTH - PADDING.right} y={y - 4} fill={line.color} fontSize="10" textAnchor="end">{line.label}</text></g>; })}<line x1={PADDING.left} x2={PADDING.left} y1={PADDING.top} y2={HEIGHT - PADDING.bottom} stroke="#cbd5e1" /><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={HEIGHT - PADDING.bottom} y2={HEIGHT - PADDING.bottom} stroke="#cbd5e1" />{visible.map((dataset) => <path key={dataset.key} d={pathFor(dataset.key)} fill="none" stroke={dataset.color} strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" />)}{points.map(({ point, x }) => <g key={point.date}>{visible.map((dataset) => { const value = valueFor(point, dataset.key); return value === null ? null : <circle key={dataset.key} cx={x} cy={yFor(value, bounds, plotHeight)} r={selectedDate === point.date ? 4 : 2.5} fill={dataset.color} stroke="white" strokeWidth="1.5" tabIndex={0} role="button" aria-label={`${point.date}: ${dataset.label} ${format(value)} ${unit}`} onMouseEnter={() => setSelectedDate(point.date)} onClick={() => setSelectedDate(point.date)} onKeyDown={(event) => activateOnKey(event, () => setSelectedDate(point.date))}><title>{`${point.date}: ${format(value)} ${unit} · ${dataset.label}`}</title></circle>; })}</g>)}{labels(series).map((point) => { const x = PADDING.left + (series.length === 1 ? plotWidth / 2 : (series.indexOf(point) / (series.length - 1)) * plotWidth); return <text key={`${point.date}-label`} x={x} y={HEIGHT - 16} fill="#64748b" fontSize="10" textAnchor="middle">{point.day}</text>; })}<text x="14" y={HEIGHT / 2} fill="#64748b" fontSize="10" textAnchor="middle" transform={`rotate(-90 14 ${HEIGHT / 2})`}>{unit}</text><text x={WIDTH / 2} y={HEIGHT - 2} fill="#64748b" fontSize="10" textAnchor="middle">Tanggal</text>
  </svg>{selectedDate ? <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600"><strong className="text-slate-900">{selectedDate}</strong>{visible.map((dataset) => { const point = series.find((item) => item.date === selectedDate); const value = point ? valueFor(point, dataset.key) : null; return value === null ? null : <span key={dataset.key}>{dataset.label}: <strong className="text-slate-900">{format(value)} {unit}</strong></span>; })}</div> : null}</div>;
}

export function DetailBarChart({ series, datasets, unit, stacked = false }: DetailBarChartProps) {
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [hiddenKeys, setHiddenKeys] = useState<Set<SeriesKey>>(new Set());
  const visible = datasets.filter((dataset) => !hiddenKeys.has(dataset.key));
  const hasValue = visible.some((dataset) => series.some((point) => valueFor(point, dataset.key) !== null));
  if (!hasValue) return <EmptyChart message="Pilih minimal satu series untuk divisualisasikan." />;
  const totals = series.map((point) => stacked ? visible.reduce((total, dataset) => total + Math.max(0, valueFor(point, dataset.key) ?? 0), 0) : Math.max(...visible.map((dataset) => valueFor(point, dataset.key) ?? 0), 0));
  const bounds = chartBounds(totals);
  const plotWidth = WIDTH - PADDING.left - PADDING.right;
  const plotHeight = HEIGHT - PADDING.top - PADDING.bottom;
  const groupWidth = plotWidth / Math.max(series.length, 1);
  const barWidth = Math.max(2, Math.min(18, groupWidth * (stacked ? 0.62 : 0.8) / visible.length));
  const selected = selectedDate ? series.find((point) => point.date === selectedDate) : null;
  return <div className="rounded-xl border border-slate-100 bg-slate-50/60 p-2 sm:p-3"><div className="mb-2 flex flex-wrap items-center justify-end gap-2 px-2 text-xs text-slate-600">{datasets.map((dataset) => <button key={dataset.key} type="button" aria-pressed={!hiddenKeys.has(dataset.key)} onClick={() => setHiddenKeys((current) => { const next = new Set(current); if (next.has(dataset.key)) next.delete(dataset.key); else if (next.size < datasets.length - 1) next.add(dataset.key); return next; })} className={`inline-flex min-h-8 items-center gap-2 rounded-lg px-2 py-1 transition focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 ${hiddenKeys.has(dataset.key) ? "text-slate-400 line-through" : "hover:bg-white"}`}><i className="size-2 rounded-full" style={{ backgroundColor: hiddenKeys.has(dataset.key) ? "#cbd5e1" : dataset.color }} />{dataset.label}</button>)}</div><svg className="h-auto w-full" viewBox={`0 0 ${WIDTH} ${HEIGHT}`} role="img" aria-label={`Grafik ${datasets.map((dataset) => dataset.label).join(", ")}`}>
    {[0, 0.25, 0.5, 0.75, 1].map((ratio) => { const y = PADDING.top + plotHeight * ratio; const value = bounds.max - (bounds.max - bounds.min) * ratio; return <g key={ratio}><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={y} y2={y} stroke="#e2e8f0" strokeDasharray="4 4" /><text x={PADDING.left - 8} y={y + 4} fill="#64748b" fontSize="10" textAnchor="end">{format(value)}</text></g>; })}<line x1={PADDING.left} x2={PADDING.left} y1={PADDING.top} y2={HEIGHT - PADDING.bottom} stroke="#cbd5e1" /><line x1={PADDING.left} x2={WIDTH - PADDING.right} y1={HEIGHT - PADDING.bottom} y2={HEIGHT - PADDING.bottom} stroke="#cbd5e1" />{series.map((point, index) => { const center = PADDING.left + index * groupWidth + groupWidth / 2; let stack = 0; return <g key={point.date}>{visible.map((dataset, datasetIndex) => { const value = valueFor(point, dataset.key); if (value === null) return null; const positiveValue = Math.max(0, value); const height = (positiveValue / (bounds.max - bounds.min)) * plotHeight; const x = stacked ? center - barWidth / 2 : center - (visible.length * barWidth) / 2 + datasetIndex * barWidth; const y = stacked ? PADDING.top + plotHeight - ((stack + positiveValue) / (bounds.max - bounds.min)) * plotHeight : PADDING.top + plotHeight - height; if (stacked) stack += positiveValue; return <rect key={dataset.key} x={x} y={y} width={barWidth} height={height} rx="2" fill={dataset.color} opacity={selectedDate === point.date ? 1 : 0.88} tabIndex={0} role="button" aria-label={`${point.date}: ${dataset.label} ${format(value)} ${unit}`} onMouseEnter={() => setSelectedDate(point.date)} onClick={() => setSelectedDate(point.date)} onKeyDown={(event) => activateOnKey(event, () => setSelectedDate(point.date))}><title>{`${point.date}: ${format(value)} ${unit} · ${dataset.label}`}</title></rect>; })}</g>; })}{labels(series).map((point) => { const x = PADDING.left + series.indexOf(point) * groupWidth + groupWidth / 2; return <text key={`${point.date}-label`} x={x} y={HEIGHT - 16} fill="#64748b" fontSize="10" textAnchor="middle">{point.day}</text>; })}<text x="14" y={HEIGHT / 2} fill="#64748b" fontSize="10" textAnchor="middle" transform={`rotate(-90 14 ${HEIGHT / 2})`}>{unit}</text><text x={WIDTH / 2} y={HEIGHT - 2} fill="#64748b" fontSize="10" textAnchor="middle">Tanggal</text>
  </svg>{selected ? <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600"><strong className="text-slate-900">{selected.date}</strong>{visible.map((dataset) => { const value = valueFor(selected, dataset.key); return value === null ? null : <span key={dataset.key}>{dataset.label}: <strong className="text-slate-900">{format(value)} {unit}</strong></span>; })}</div> : <p className="mt-2 px-2 text-[11px] text-slate-400">Arahkan atau pilih bar untuk melihat detail.</p>}</div>;
}

export function TargetProgressChart({ progress }: { progress: number }) {
  const safeProgress = Math.min(100, Math.max(0, progress));
  const radius = 72;
  const circumference = 2 * Math.PI * radius;
  return <div className="flex h-64 items-center justify-center"><svg viewBox="0 0 200 200" className="h-56 w-56" role="img" aria-label={`Progress target ${safeProgress.toLocaleString("id-ID", { maximumFractionDigits: 1 })} persen`}><circle cx="100" cy="100" r={radius} fill="none" stroke="#e2e8f0" strokeWidth="22" /><circle cx="100" cy="100" r={radius} fill="none" stroke={safeProgress >= 100 ? "#16a34a" : safeProgress >= 70 ? "#f59e0b" : "#7c3aed"} strokeWidth="22" strokeLinecap="round" strokeDasharray={`${(safeProgress / 100) * circumference} ${circumference}`} transform="rotate(-90 100 100)" /><text x="100" y="96" textAnchor="middle" className="fill-slate-900 text-2xl font-bold">{safeProgress.toLocaleString("id-ID", { maximumFractionDigits: 1 })}%</text><text x="100" y="118" textAnchor="middle" className="fill-slate-500 text-[10px]">tercapai</text></svg></div>;
}
